[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    zinggjm/GxEPD2
    adafruit/Adafruit GFX Library
    bblanchon/ArduinoJson
    arduino-libraries/NTPClient
